### ISSUE TITLE
Add support for rolling evaluation in TaskGenerator

### ISSUE THREAD

**Issue by shchur** [autogluon/fev#5]
Currently, to specify multiple windows for rolling evaluation, the user needs to specify all cutoff dates using the `variants` in a `TaskGenerator`.
```yaml
tasks:
- dataset_path: ...
   horizon: 24
   variants:
   - cutoff: -96
   - cutoff: -72
   - cutoff: -48
   - cutoff: -24
```
This can be unnecessarily verbose and potentially error prone.

It would be more convenient to directly specify the backtest config, something like the following
```yaml
tasks:
- dataset_path: ...
   horizon: 24
   backtest:
     start_cutoff: -96
     num_windows: 4
     val_step_size: 24  # defaults to `horizon`
```
